.TH APPOP 1 "December 2024" "Version 1.0" "Manual Page for MyApp"
.SH NAME
myapp \- a brief description of your app
.SH SYNOPSIS
.B myapp
[options] [arguments]
.SH DESCRIPTION
MyApp is a program that does XYZ. It is used for ...
.SH OPTIONS
.TP
.B \-h, \-\-help
Show the help message and exit.
.TP
.B \-v, \-\-version
Show version information and exit.
.SH EXAMPLES
.TP
Run MyApp with default settings:
.EX
myapp
.EE
.TP
Run MyApp with a custom option:
.EX
myapp \-o custom
.EE
.SH SEE ALSO
man(1), groff(1)
.SH AUTHOR
Written by [Your Name or Organization].
.SH SEE ALSO
appop(5), apconfig(1), man(1)
